// --------------------------------------------------------- //
// Please do not edit this file. This file is autogenerated. //
// --------------------------------------------------------- //

import { ThemeContext, ThemeContextProps } from 'anoa-react-native-theme'
import { BaseTheme } from './themes'

const themes = {}

export const AppStyle = new ThemeContext(BaseTheme, themes)
export type AppThemes = typeof themes
export type AppStyleProps = ThemeContextProps<typeof BaseTheme, AppThemes>
