// tslint:disable:ordered-imports

// --------------------------------------------------------- //
// Please do not edit this file. This file is autogenerated. //
// --------------------------------------------------------- //

import { combineReducers } from 'redux'
import RestoReducer from './resto'
import RestoActions from './resto/actions'

export const reducers = combineReducers({
  resto: RestoReducer
})

export type AppRootActions = RestoActions

export type AppRootState = ReturnType<typeof reducers>
